name: リクエスト / Request
description: 新しいフォントや新たな対応文字、ドキュメントの修正などをリクエストします / Request for new fonts, additional supported characters, and document revisions
title: "[Request]: "
body:
  - type: textarea
    id: details
    attributes:
      label: リクエスト内容 / Request Details
    validations:
      required: true
  - type: dropdown
    id: label
    attributes:
      label: ラベル / Label
      options:
        - 新しい文字をリクエスト / Request a New Character
        - 新しいフォントをリクエスト / Request a New Font
        - その他 / Other
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        フィードバックありがとうございます！
        内容をもう一度確認してから提出してください。。
        Thanks for your feedback!
        Please review the details before submitting.